# Generated by Django 5.1.15 on 2026-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='github_username',
            field=models.CharField(blank=True, default='', help_text='GitHub login, if the participant shared it.', max_length=255),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='osm_username',
            field=models.CharField(blank=True, default='', help_text='OpenStreetMap (and OpenHistoricalMap) username, if the participant shared it.', max_length=255),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='wikimedia_username',
            field=models.CharField(blank=True, default='', help_text='Wikimedia account name (Commons / Wikidata), if the participant shared it.', max_length=255),
        ),
    ]
