# Generated by Django 5.1.15 on 2026-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule_url',
            field=models.URLField(blank=True, help_text='Optional pretalx/frab-compatible schedule JSON export used to link quests to sessions, e.g. https://talks.osgeo.org/foss4g-na-2026/schedule/export/schedule.json', max_length=500),
        ),
    ]
