# Generated by Django 5.1.15 on 2026-10-06 06:52

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Sum
from django.utils import timezone


def backfill_quest_progress(apps, schema_editor):
    """
    Before QuestProgress existed, verifying a submission added its quest's points to the team
    score directly. Record those already-awarded points so the first recompute does not add
    them a second time. Team scores themselves are left untouched; completed_at is only set
    where the count already meets the quest's target_count.
    """
    Submission = apps.get_model('submissions', 'Submission')
    QuestProgress = apps.get_model('submissions', 'QuestProgress')
    Quest = apps.get_model('quests', 'Quest')

    def target_count(quest_id):
        # Historical models do not carry the Quest.target_count property; mirror it here.
        rules = Quest.objects.get(pk=quest_id).validation_rules or {}
        try:
            return max(1, int(rules.get('target_count', 1)))
        except (TypeError, ValueError, AttributeError):
            return 1

    pairs = (
        Submission.objects
        .filter(is_verified=True, team__isnull=False, quest__isnull=False)
        .values('team_id', 'quest_id')
        .annotate(total=Sum('element_count'))
    )
    now = timezone.now()
    for row in pairs:
        total = row['total'] or 0
        QuestProgress.objects.update_or_create(
            team_id=row['team_id'],
            quest_id=row['quest_id'],
            defaults={
                'count': total,
                'completed_at': now if total >= target_count(row['quest_id']) else None,
                'points_awarded': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_inspired_by_quest_window_end_and_more'),
        ('submissions', '0001_initial'),
        ('teams', '0002_teammembership_github_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contributed_at',
            field=models.DateTimeField(blank=True, help_text='When the contribution happened on the external platform (created_at is when it was harvested).', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='element_count',
            field=models.PositiveIntegerField(default=1, help_text='How many distinct contributions this submission represents toward a counted quest (e.g. 3 cafes given opening_hours in one changeset).'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='platform',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('commons', 'Wikimedia Commons'), ('wikidata', 'Wikidata'), ('ohm', 'OpenHistoricalMap'), ('osm_notes', 'OpenStreetMap Notes'), ('checkin', 'GPS Check-in'), ('github', 'GitHub'), ('panoramax', 'Panoramax')], help_text='Source platform of the contribution.', max_length=16),
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text="Sum of element_count across the team's verified submissions for this quest.")),
                ('completed_at', models.DateTimeField(blank=True, help_text="When count first reached the quest's target_count (cleared if it drops below).", null=True)),
                ('points_awarded', models.BooleanField(default=False, help_text='Whether quest.points_reward is currently included in team.score.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last recompute.')),
                ('quest', models.ForeignKey(help_text='Quest being progressed.', on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='quests.quest')),
                ('team', models.ForeignKey(help_text='Team whose progress this row tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='teams.team')),
            ],
            options={
                'verbose_name': 'Quest Progress',
                'verbose_name_plural': 'Quest Progress',
                'ordering': ['quest__title'],
                'unique_together': {('team', 'quest')},
            },
        ),
        migrations.RunPython(backfill_quest_progress, migrations.RunPython.noop),
    ]
