# Generated by Django 5.1.15 on 2026-10-06 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_inspired_by_quest_window_end_and_more'),
        ('submissions', '0002_submission_contributed_at_submission_element_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedOsmElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], help_text='OSM element type.', max_length=8)),
                ('element_id', models.BigIntegerField(help_text='OSM element id.')),
                ('last_seen_version', models.PositiveIntegerField(default=1, help_text='Highest element version seen by the harvester; a higher one triggers a new history lookup.')),
                ('created_at_osm', models.DateTimeField(blank=True, help_text='Timestamp of version 1 (null when the history did not include it).', null=True)),
                ('creator_username', models.CharField(blank=True, default='', help_text='User who created the element (version 1).', max_length=255)),
                ('creation_changeset', models.BigIntegerField(blank=True, help_text='Changeset that created the element (version 1).', null=True)),
                ('last_editor_username', models.CharField(blank=True, default='', help_text='User who made the latest version seen.', max_length=255)),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='When the harvester last saw the element.')),
                ('quest', models.ForeignKey(help_text='Quest the element was matched for.', on_delete=django.db.models.deletion.CASCADE, related_name='tracked_osm_elements', to='quests.quest')),
            ],
            options={
                'verbose_name': 'Tracked OSM Element',
                'verbose_name_plural': 'Tracked OSM Elements',
                'unique_together': {('quest', 'element_type', 'element_id')},
            },
        ),
    ]
