# Generated by Django 5.1.15 on 2026-10-06 22:22

from django.db import migrations, models


def backfill_awarded_points(apps, schema_editor):
    """Rows that had the completion points awarded hold quest.points_reward of the team score."""
    QuestProgress = apps.get_model('submissions', 'QuestProgress')
    for progress in QuestProgress.objects.filter(points_awarded=True).select_related('quest'):
        progress.awarded_points = progress.quest.points_reward
        progress.save(update_fields=['awarded_points'])


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_trackedosmelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='questprogress',
            name='awarded_points',
            field=models.IntegerField(default=0, help_text='Points the team currently holds from this quest: completion points plus any value-scoring bucket points and extreme bonus. team.score moves by the change in this value.'),
        ),
        migrations.AddField(
            model_name='questprogress',
            name='best_value',
            field=models.FloatField(blank=True, help_text="The team's extreme verified value on a value-scoring quest (min or max per the rule).", null=True),
        ),
        migrations.AddField(
            model_name='questprogress',
            name='buckets',
            field=models.JSONField(blank=True, default=list, help_text='Value-scoring buckets found (bucket starts, e.g. [1920, 1950] for decades), sorted.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_value',
            field=models.FloatField(blank=True, help_text="Value read for a value-scoring quest (validation_rules.scoring), e.g. the year on a sidewalk stamp. For element-based submissions this is the extreme of the per-element values stored in diff_payload['extracted_values']. Hosts can correct it when verifying.", null=True),
        ),
        migrations.AlterField(
            model_name='questprogress',
            name='points_awarded',
            field=models.BooleanField(default=False, help_text='Whether quest.points_reward (the completion points) is currently included in team.score.'),
        ),
        migrations.RunPython(backfill_awarded_points, migrations.RunPython.noop),
    ]
