# Generated by Django 5.1.15 on 2026-10-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_value_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='platform',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('commons', 'Wikimedia Commons'), ('wikidata', 'Wikidata'), ('ohm', 'OpenHistoricalMap'), ('osm_notes', 'OpenStreetMap Notes'), ('checkin', 'GPS Check-in'), ('github', 'GitHub'), ('panoramax', 'Panoramax'), ('mangrove', 'Mangrove Reviews'), ('maproulette', 'MapRoulette')], help_text='Source platform of the contribution.', max_length=16),
        ),
    ]
