# Generated by Django 5.1.15 on 2026-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='inspired_by',
            field=models.JSONField(blank=True, default=dict, help_text='Conference session that inspired this quest (empty when none). Shape: {"code": "ABC123", "title": "Talk title", "speakers": ["Name"], "start": "2026-11-03T16:00:00-08:00", "room": "Room name", "track": "Track name", "url": "https://talks.example.org/talk/ABC123/"}'),
        ),
        migrations.AddField(
            model_name='quest',
            name='window_end',
            field=models.DateTimeField(blank=True, help_text='Optional end of a quest-specific time window inside the event window.', null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='window_start',
            field=models.DateTimeField(blank=True, help_text='Optional start of a quest-specific time window inside the event window (e.g. Monday evening only).', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='criteria_type',
            field=models.CharField(choices=[('osm_tags', 'OpenStreetMap Tag Rule'), ('wikimedia_commons', 'Wikimedia Commons Photo'), ('wikidata_entry', 'Wikidata Item Edit'), ('location_checkin', 'GPS Check-in'), ('osm_notes', 'OpenStreetMap Note Resolved'), ('ohm_feature', 'OpenHistoricalMap Feature'), ('wikidata_statement', 'Wikidata Statement on Item'), ('oss_contribution', 'Open Source Contribution (GitHub)'), ('street_imagery', 'Street-level Imagery (Panoramax)')], default='osm_tags', help_text='Platform and verification type for this quest.', max_length=32),
        ),
    ]
