# Generated by Django 5.1.15 on 2026-10-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_mangrove_maproulette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='criteria_type',
            field=models.CharField(choices=[('osm_tags', 'OpenStreetMap Tag Rule'), ('wikimedia_commons', 'Wikimedia Commons Photo'), ('wikidata_entry', 'Wikidata Item Edit'), ('location_checkin', 'GPS Check-in'), ('osm_notes', 'OpenStreetMap Note Resolved'), ('ohm_feature', 'OpenHistoricalMap Feature'), ('wikidata_statement', 'Wikidata Statement on Item'), ('oss_contribution', 'Open Source Contribution (GitHub)'), ('street_imagery', 'Street-level Imagery (Panoramax)'), ('mangrove_review', 'Mangrove Place Review'), ('maproulette_task', 'MapRoulette Task Fixed'), ('wikidata_area', 'Wikidata statements on items in the area (images via WikiShootMe)')], default='osm_tags', help_text='Platform and verification type for this quest.', max_length=32),
        ),
    ]
